apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qn47xd2zh-nodejs
  janus-idp.io/tekton: qn47xd2zh-nodejs
  backstage.io/kubernetes-id: qn47xd2zh-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qn47xd2zh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
